# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2018.2
# Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================


/media/mariko/external_storage_personal/ece496/Xilinx/Vivado/2018.2/bin/vivado  -notrace -mode batch -source run_ippack.tcl
