# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir G:/ECE532/initial_demo/initial_demo.cache/wt [current_project]
set_property parent.project_path G:/ECE532/initial_demo/initial_demo.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.1 [current_project]
set_property ip_repo_paths {
  g:/ECE532/temp_milestone.xpr/project_1/project_1.ipdefs/repo_0_0
  g:/ECE532/temp_milestone.xpr/project_1/project_1.ipdefs/input_from_mb_extended_0_0_0
  g:/ECE532/temp_milestone.xpr/project_1/project_1.ipdefs/impl_0_0
} [current_project]
set_property ip_output_repo g:/ECE532/initial_demo/initial_demo.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib G:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/hdl/hdmi_wrapper.v
add_files G:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/hdmi.bd
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_gpio_video_0/hdmi_axi_gpio_video_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_gpio_video_0/hdmi_axi_gpio_video_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_gpio_video_0/hdmi_axi_gpio_video_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_timer_0_0/hdmi_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_timer_0_0/hdmi_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_uartlite_0_0/hdmi_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_uartlite_0_0/hdmi_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_uartlite_0_0/hdmi_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_vdma_0_0/hdmi_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_vdma_0_0/hdmi_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_vdma_0_0/hdmi_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/dvi2rgb.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_mdm_1_0/hdmi_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_mdm_1_0/hdmi_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_microblaze_0_0/hdmi_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_microblaze_0_0/hdmi_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_microblaze_0_0/hdmi_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_microblaze_0_axi_intc_0/hdmi_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_microblaze_0_axi_intc_0/hdmi_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_microblaze_0_axi_intc_0/hdmi_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/constraints/hdmi_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/constraints/hdmi_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_rgb2dvi_0_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_rst_mig_7series_0_100M_0/hdmi_rst_mig_7series_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_rst_mig_7series_0_100M_0/hdmi_rst_mig_7series_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_rst_mig_7series_0_100M_0/hdmi_rst_mig_7series_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_rst_mig_7series_0_pxl_0/hdmi_rst_mig_7series_0_pxl_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_rst_mig_7series_0_pxl_0/hdmi_rst_mig_7series_0_pxl_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_rst_mig_7series_0_pxl_0/hdmi_rst_mig_7series_0_pxl_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_v_axi4s_vid_out_0_0/hdmi_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_v_axi4s_vid_out_0_0/hdmi_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_v_tc_0_0/hdmi_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_v_tc_0_0/hdmi_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_v_tc_1_0/hdmi_v_tc_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_v_tc_1_0/hdmi_v_tc_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_v_vid_in_axi4s_0_0/hdmi_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_v_vid_in_axi4s_0_0/hdmi_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_dlmb_bram_if_cntlr_0/hdmi_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_dlmb_v10_0/hdmi_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_dlmb_v10_0/hdmi_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_ilmb_bram_if_cntlr_0/hdmi_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_ilmb_v10_0/hdmi_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_ilmb_v10_0/hdmi_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_lmb_bram_0/hdmi_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_xbar_1/hdmi_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_xbar_0/hdmi_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_clk_wiz_0_0/hdmi_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_clk_wiz_0_0/hdmi_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_clk_wiz_0_0/hdmi_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_rst_clk_wiz_0_100M_0/hdmi_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_rst_clk_wiz_0_100M_0/hdmi_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_rst_clk_wiz_0_100M_0/hdmi_rst_clk_wiz_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/ip/ip_0/bd_e87d_eth_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/ip/ip_0/synth/bd_e87d_eth_buf_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/ip/ip_0/bd_e87d_eth_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_e87d_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_e87d_mac_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_e87d_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_e87d_mac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/ip/ip_2/bd_e87d_c_shift_ram_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/ip/ip_3/bd_e87d_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/bd_0/bd_e87d_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/hdmi_axi_ethernet_0_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_0/synth/hdmi_axi_ethernet_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_dma_0/hdmi_axi_ethernet_0_dma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_dma_0/hdmi_axi_ethernet_0_dma_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_ethernet_0_dma_0/hdmi_axi_ethernet_0_dma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_vdma_1_0/hdmi_axi_vdma_1_0.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_vdma_1_0/hdmi_axi_vdma_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_vdma_1_0/hdmi_axi_vdma_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_fifo_mm_s_0_0/hdmi_axi_fifo_mm_s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axis_dwidth_converter_0_0/hdmi_axis_dwidth_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_det_color_cord_0_1/constraints/det_color_cord.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_det_color_cord_0_1/constraints/det_color_cord_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_uartlite_1_0/hdmi_axi_uartlite_1_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_uartlite_1_0/hdmi_axi_uartlite_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_axi_uartlite_1_0/hdmi_axi_uartlite_1_0.xdc]
set_property used_in_synthesis false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_cc_4/hdmi_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_cc_4/hdmi_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_cc_4/hdmi_auto_cc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_m00_regslice_0/hdmi_m00_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_m00_regslice_0/hdmi_m00_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_ds_0/hdmi_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_ds_0/hdmi_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_ds_0/hdmi_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_rs_w_0/hdmi_auto_rs_w_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_rs_w_0/hdmi_auto_rs_w_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_6/hdmi_auto_us_6_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_6/hdmi_auto_us_6_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_6/hdmi_auto_us_6_ooc.xdc]
set_property used_in_synthesis false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_cc_3/hdmi_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_cc_3/hdmi_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_cc_3/hdmi_auto_cc_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_5/hdmi_auto_us_5_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_5/hdmi_auto_us_5_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_5/hdmi_auto_us_5_ooc.xdc]
set_property used_in_synthesis false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_cc_2/hdmi_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_cc_2/hdmi_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_cc_2/hdmi_auto_cc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_4/hdmi_auto_us_4_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_4/hdmi_auto_us_4_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_4/hdmi_auto_us_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_cc_1/hdmi_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_cc_1/hdmi_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_cc_1/hdmi_auto_cc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_3/hdmi_auto_us_3_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_3/hdmi_auto_us_3_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_3/hdmi_auto_us_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_cc_0/hdmi_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_cc_0/hdmi_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_cc_0/hdmi_auto_cc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_2/hdmi_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_2/hdmi_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_2/hdmi_auto_us_2_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_s03_regslice_0/hdmi_s03_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_s03_regslice_0/hdmi_s03_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_s02_regslice_0/hdmi_s02_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_s02_regslice_0/hdmi_s02_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_s01_regslice_0/hdmi_s01_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_s01_regslice_0/hdmi_s01_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_1/hdmi_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_1/hdmi_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_1/hdmi_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_rs_w_2/hdmi_auto_rs_w_2_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_rs_w_2/hdmi_auto_rs_w_2_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_s00_regslice_0/hdmi_s00_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_s00_regslice_0/hdmi_s00_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_0/hdmi_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_0/hdmi_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_0/hdmi_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_rs_w_1/hdmi_auto_rs_w_1_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/ip/hdmi_auto_rs_w_1/hdmi_auto_rs_w_1_ooc.xdc]
set_property used_in_implementation false [get_files -all G:/ECE532/initial_demo/initial_demo.srcs/sources_1/bd/hdmi/hdmi_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/ECE532/initial_demo/initial_demo.srcs/constrs_1/imports/constraints/NexysVideo_Master.xdc
set_property used_in_implementation false [get_files G:/ECE532/initial_demo/initial_demo.srcs/constrs_1/imports/constraints/NexysVideo_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top hdmi_wrapper -part xc7a200tsbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef hdmi_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file hdmi_wrapper_utilization_synth.rpt -pb hdmi_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
