-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity det_color_cord is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    frame_in_V_dout : IN STD_LOGIC_VECTOR (27 downto 0);
    frame_in_V_empty_n : IN STD_LOGIC;
    frame_in_V_read : OUT STD_LOGIC;
    cord_out_V_din : OUT STD_LOGIC_VECTOR (96 downto 0);
    cord_out_V_full_n : IN STD_LOGIC;
    cord_out_V_write : OUT STD_LOGIC;
    target_threshold : IN STD_LOGIC_VECTOR (7 downto 0);
    other_threshold : IN STD_LOGIC_VECTOR (7 downto 0);
    target_color : IN STD_LOGIC_VECTOR (7 downto 0);
    width : IN STD_LOGIC_VECTOR (31 downto 0);
    height : IN STD_LOGIC_VECTOR (31 downto 0);
    reset : IN STD_LOGIC;
    y_cord_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    y_cord_out_ap_vld : OUT STD_LOGIC;
    x_cord_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    x_cord_out_ap_vld : OUT STD_LOGIC;
    pixel_in_data_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    pixel_in_data_out_ap_vld : OUT STD_LOGIC;
    edgeout_val : OUT STD_LOGIC_VECTOR (63 downto 0);
    edgeout_val_ap_vld : OUT STD_LOGIC );
end;


architecture behav of det_color_cord is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "det_color_cord,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a200tsbg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.782000,HLS_SYN_LAT=2,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=980,HLS_SYN_LUT=1835,HLS_VERSION=2018_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv8_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000011";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv64_FFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000011111111111111111111111111111111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

    signal current_x_cord : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal current_y_cord : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal left_edge : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal upper_edge : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal bottom_edge : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal right_edge : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal led_exist : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal frame_in_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal tmp_nbreadreq_fu_154_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal cord_out_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_reg_1168 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_1176 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1181 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal p_current_x_cord_load_fu_466_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_current_x_cord_load_reg_1099 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_current_y_cord_load_fu_474_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_current_y_cord_load_reg_1111 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_488_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_1124 : STD_LOGIC_VECTOR (0 downto 0);
    signal width_left_edge_load_fu_510_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal width_left_edge_load_reg_1140 : STD_LOGIC_VECTOR (31 downto 0);
    signal height_upper_edge_lo_fu_518_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal height_upper_edge_lo_reg_1147 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_bottom_edge_load_fu_526_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_bottom_edge_load_reg_1154 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_right_edge_load_fu_534_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_right_edge_load_reg_1161 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_cond_7_fu_687_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_7_reg_1172 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_810_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_fu_453_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal led_exist_load_reg_1185 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_819_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_11_reg_1190 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_14_fu_825_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_14_reg_1197 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_4_fu_867_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_4_reg_1204 : STD_LOGIC_VECTOR (63 downto 0);
    signal left_edge_flag_1_fu_728_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal left_edge_flag_2_reg_203 : STD_LOGIC_VECTOR (0 downto 0);
    signal width_assign_fu_734_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal left_edge_new_2_reg_213 : STD_LOGIC_VECTOR (31 downto 0);
    signal left_edge_loc_1_fu_741_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_left_edge_loc_2_phi_fu_226_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal left_edge_loc_2_reg_223 : STD_LOGIC_VECTOR (31 downto 0);
    signal upper_edge_flag_1_fu_777_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal upper_edge_flag_2_reg_232 : STD_LOGIC_VECTOR (0 downto 0);
    signal height_assign_fu_783_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal upper_edge_new_2_reg_242 : STD_LOGIC_VECTOR (31 downto 0);
    signal upper_edge_loc_1_fu_790_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_upper_edge_loc_2_phi_fu_255_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal upper_edge_loc_2_reg_252 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_left_edge_flag1_fu_752_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bottom_edge_flag_2_reg_261 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_current_y_cord_load_1_fu_758_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal bottom_edge_new_2_reg_271 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_current_y_cord_load_2_fu_766_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_bottom_edge_loc_2_phi_fu_286_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal bottom_edge_loc_2_reg_283 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_left_edge_flag_fu_703_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal right_edge_flag_2_reg_292 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_current_x_cord_load_1_fu_709_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal right_edge_new_2_reg_302 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_current_x_cord_load_2_fu_717_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_right_edge_loc_2_phi_fu_317_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal right_edge_loc_2_reg_314 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_current_x_cord_flag_1_phi_fu_326_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal current_x_cord_flag_1_reg_323 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op141_write_state3 : BOOLEAN;
    signal ap_block_state3 : BOOLEAN;
    signal storemerge_fu_1030_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_current_x_cord_new_1_phi_fu_337_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_x_cord_new_1_reg_333 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_y_cord_flag_1_fu_1007_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_current_y_cord_flag_2_phi_fu_347_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal current_y_cord_flag_2_reg_344 : STD_LOGIC_VECTOR (0 downto 0);
    signal current_y_cord_new_1_fu_1013_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_current_y_cord_new_2_phi_fu_357_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_y_cord_new_2_reg_353 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_left_edge_flag_3_phi_fu_367_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal left_edge_flag_3_reg_364 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_left_edge_new_3_phi_fu_377_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal left_edge_new_3_reg_374 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_upper_edge_flag_3_phi_fu_387_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal upper_edge_flag_3_reg_384 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_upper_edge_new_3_phi_fu_397_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal upper_edge_new_3_reg_394 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_bottom_edge_flag_3_phi_fu_407_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal bottom_edge_flag_3_reg_404 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_bottom_edge_new_3_phi_fu_418_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal bottom_edge_new_3_reg_414 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_right_edge_flag_3_phi_fu_429_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal right_edge_flag_3_reg_426 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_right_edge_new_3_phi_fu_440_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal right_edge_new_3_reg_436 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_448_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_current_x_cord_load_fu_466_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_current_y_cord_load_fu_474_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_482_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_21_fu_542_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sel_tmp4_fu_587_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_cast_fu_555_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_fu_565_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sel_tmp2_fu_581_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_fu_575_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_1_fu_551_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_cond_fu_601_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel_fu_593_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel1_fu_607_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel3_fu_623_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel4_fu_631_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_647_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_3_fu_655_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_2_fu_639_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal newSel2_fu_615_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal other2_below_fu_663_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal target_above_fu_675_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_681_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal other1_below_fu_669_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_699_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_724_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_748_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_773_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_805_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_34_fu_835_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_29_fu_797_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_22_fu_839_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_33_fu_831_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_30_fu_801_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_23_fu_851_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal ud_edge_fu_847_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal val_assign_fu_861_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_neg1_fu_882_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_12_fu_887_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_31_fu_875_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_897_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_15_fu_903_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_neg_fu_927_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_17_fu_932_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_32_fu_920_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_fu_942_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_19_fu_948_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_16_fu_912_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_20_fu_957_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_center_V_fu_965_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_fu_973_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_26_fu_990_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_y_cord_flag_1_fu_1007_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge1_fu_995_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_27_fu_1002_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    bottom_edge_flag_2_reg_261_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (or_cond_7_fu_687_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                bottom_edge_flag_2_reg_261 <= tmp_4_fu_488_p2;
            elsif (((or_cond_7_reg_1172 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                bottom_edge_flag_2_reg_261 <= p_left_edge_flag1_fu_752_p2;
            end if; 
        end if;
    end process;

    bottom_edge_flag_3_reg_404_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                bottom_edge_flag_3_reg_404 <= tmp_4_fu_488_p2;
            elsif ((not(((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0))) and (tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                bottom_edge_flag_3_reg_404 <= bottom_edge_flag_2_reg_261;
            end if; 
        end if;
    end process;

    bottom_edge_loc_2_reg_283_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (or_cond_7_fu_687_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                bottom_edge_loc_2_reg_283 <= p_bottom_edge_load_fu_526_p3;
            elsif (((or_cond_7_reg_1172 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                bottom_edge_loc_2_reg_283 <= p_current_y_cord_load_2_fu_766_p3;
            end if; 
        end if;
    end process;

    bottom_edge_new_2_reg_271_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (or_cond_7_fu_687_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                bottom_edge_new_2_reg_271 <= ap_const_lv32_0;
            elsif (((or_cond_7_reg_1172 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                bottom_edge_new_2_reg_271 <= p_current_y_cord_load_1_fu_758_p3;
            end if; 
        end if;
    end process;

    bottom_edge_new_3_reg_414_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                bottom_edge_new_3_reg_414 <= ap_const_lv32_0;
            elsif ((not(((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0))) and (tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                bottom_edge_new_3_reg_414 <= bottom_edge_new_2_reg_271;
            end if; 
        end if;
    end process;

    current_x_cord_flag_1_reg_323_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                current_x_cord_flag_1_reg_323 <= (0=>reset, others=>'-');
            elsif ((not(((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0))) and (tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                current_x_cord_flag_1_reg_323 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    current_x_cord_new_1_reg_333_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                current_x_cord_new_1_reg_333 <= ap_const_lv32_0;
            elsif ((not(((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0))) and (tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                current_x_cord_new_1_reg_333 <= storemerge_fu_1030_p3;
            end if; 
        end if;
    end process;

    current_y_cord_flag_2_reg_344_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                current_y_cord_flag_2_reg_344 <= (0=>reset, others=>'-');
            elsif ((not(((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0))) and (tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                current_y_cord_flag_2_reg_344 <= current_y_cord_flag_1_fu_1007_p2;
            end if; 
        end if;
    end process;

    current_y_cord_new_2_reg_353_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                current_y_cord_new_2_reg_353 <= ap_const_lv32_0;
            elsif ((not(((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0))) and (tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                current_y_cord_new_2_reg_353 <= current_y_cord_new_1_fu_1013_p3;
            end if; 
        end if;
    end process;

    left_edge_flag_2_reg_203_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (or_cond_7_fu_687_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                left_edge_flag_2_reg_203 <= tmp_4_fu_488_p2;
            elsif (((or_cond_7_reg_1172 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                left_edge_flag_2_reg_203 <= left_edge_flag_1_fu_728_p2;
            end if; 
        end if;
    end process;

    left_edge_flag_3_reg_364_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                left_edge_flag_3_reg_364 <= tmp_4_fu_488_p2;
            elsif ((not(((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0))) and (tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                left_edge_flag_3_reg_364 <= left_edge_flag_2_reg_203;
            end if; 
        end if;
    end process;

    left_edge_loc_2_reg_223_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (or_cond_7_fu_687_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                left_edge_loc_2_reg_223 <= width_left_edge_load_fu_510_p3;
            elsif (((or_cond_7_reg_1172 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                left_edge_loc_2_reg_223 <= left_edge_loc_1_fu_741_p3;
            end if; 
        end if;
    end process;

    left_edge_new_2_reg_213_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (or_cond_7_fu_687_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                left_edge_new_2_reg_213 <= width;
            elsif (((or_cond_7_reg_1172 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                left_edge_new_2_reg_213 <= width_assign_fu_734_p3;
            end if; 
        end if;
    end process;

    left_edge_new_3_reg_374_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                left_edge_new_3_reg_374 <= width;
            elsif ((not(((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0))) and (tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                left_edge_new_3_reg_374 <= left_edge_new_2_reg_213;
            end if; 
        end if;
    end process;

    right_edge_flag_2_reg_292_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (or_cond_7_fu_687_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                right_edge_flag_2_reg_292 <= tmp_4_fu_488_p2;
            elsif (((or_cond_7_reg_1172 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                right_edge_flag_2_reg_292 <= p_left_edge_flag_fu_703_p2;
            end if; 
        end if;
    end process;

    right_edge_flag_3_reg_426_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                right_edge_flag_3_reg_426 <= tmp_4_fu_488_p2;
            elsif ((not(((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0))) and (tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                right_edge_flag_3_reg_426 <= right_edge_flag_2_reg_292;
            end if; 
        end if;
    end process;

    right_edge_loc_2_reg_314_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (or_cond_7_fu_687_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                right_edge_loc_2_reg_314 <= p_right_edge_load_fu_534_p3;
            elsif (((or_cond_7_reg_1172 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                right_edge_loc_2_reg_314 <= p_current_x_cord_load_2_fu_717_p3;
            end if; 
        end if;
    end process;

    right_edge_new_2_reg_302_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (or_cond_7_fu_687_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                right_edge_new_2_reg_302 <= ap_const_lv32_0;
            elsif (((or_cond_7_reg_1172 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                right_edge_new_2_reg_302 <= p_current_x_cord_load_1_fu_709_p3;
            end if; 
        end if;
    end process;

    right_edge_new_3_reg_436_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                right_edge_new_3_reg_436 <= ap_const_lv32_0;
            elsif ((not(((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0))) and (tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                right_edge_new_3_reg_436 <= right_edge_new_2_reg_302;
            end if; 
        end if;
    end process;

    upper_edge_flag_2_reg_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (or_cond_7_fu_687_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                upper_edge_flag_2_reg_232 <= tmp_4_fu_488_p2;
            elsif (((or_cond_7_reg_1172 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                upper_edge_flag_2_reg_232 <= upper_edge_flag_1_fu_777_p2;
            end if; 
        end if;
    end process;

    upper_edge_flag_3_reg_384_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                upper_edge_flag_3_reg_384 <= tmp_4_fu_488_p2;
            elsif ((not(((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0))) and (tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                upper_edge_flag_3_reg_384 <= upper_edge_flag_2_reg_232;
            end if; 
        end if;
    end process;

    upper_edge_loc_2_reg_252_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (or_cond_7_fu_687_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                upper_edge_loc_2_reg_252 <= height_upper_edge_lo_fu_518_p3;
            elsif (((or_cond_7_reg_1172 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                upper_edge_loc_2_reg_252 <= upper_edge_loc_1_fu_790_p3;
            end if; 
        end if;
    end process;

    upper_edge_new_2_reg_242_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (or_cond_7_fu_687_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                upper_edge_new_2_reg_242 <= height;
            elsif (((or_cond_7_reg_1172 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                upper_edge_new_2_reg_242 <= height_assign_fu_783_p3;
            end if; 
        end if;
    end process;

    upper_edge_new_3_reg_394_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                upper_edge_new_3_reg_394 <= height;
            elsif ((not(((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0))) and (tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                upper_edge_new_3_reg_394 <= upper_edge_new_2_reg_242;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0))) and (ap_phi_mux_bottom_edge_flag_3_phi_fu_407_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                bottom_edge <= ap_phi_mux_bottom_edge_new_3_phi_fu_418_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0))) and (ap_phi_mux_current_x_cord_flag_1_phi_fu_326_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                current_x_cord <= ap_phi_mux_current_x_cord_new_1_phi_fu_337_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0))) and (ap_phi_mux_current_y_cord_flag_2_phi_fu_347_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                current_y_cord <= ap_phi_mux_current_y_cord_new_2_phi_fu_357_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                height_upper_edge_lo_reg_1147 <= height_upper_edge_lo_fu_518_p3;
                p_bottom_edge_load_reg_1154 <= p_bottom_edge_load_fu_526_p3;
                p_current_x_cord_load_reg_1099 <= p_current_x_cord_load_fu_466_p3;
                p_current_y_cord_load_reg_1111 <= p_current_y_cord_load_fu_474_p3;
                p_right_edge_load_reg_1161 <= p_right_edge_load_fu_534_p3;
                tmp_4_reg_1124 <= tmp_4_fu_488_p2;
                tmp_reg_1168 <= (0=>frame_in_V_empty_n, others=>'-');
                width_left_edge_load_reg_1140 <= width_left_edge_load_fu_510_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (or_cond_7_fu_687_p2 = ap_const_lv1_1) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                led_exist <= ap_const_lv1_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_5_fu_810_p2 = ap_const_lv1_1) and (grp_fu_453_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                led_exist_load_reg_1185 <= led_exist;
                p_4_reg_1204 <= p_4_fu_867_p3;
                tmp_11_reg_1190 <= tmp_11_fu_819_p2;
                tmp_14_reg_1197 <= tmp_14_fu_825_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0))) and (ap_phi_mux_left_edge_flag_3_phi_fu_367_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                left_edge <= ap_phi_mux_left_edge_new_3_phi_fu_377_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                or_cond_7_reg_1172 <= or_cond_7_fu_687_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0))) and (ap_phi_mux_right_edge_flag_3_phi_fu_429_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                right_edge <= ap_phi_mux_right_edge_new_3_phi_fu_440_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_5_fu_810_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                tmp_10_reg_1181 <= grp_fu_453_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                tmp_5_reg_1176 <= tmp_5_fu_810_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0))) and (ap_phi_mux_upper_edge_flag_3_phi_fu_387_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                upper_edge <= ap_phi_mux_upper_edge_new_3_phi_fu_397_p4;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (frame_in_V_empty_n, cord_out_V_full_n, ap_CS_fsm, ap_CS_fsm_state1, tmp_nbreadreq_fu_154_p3, ap_CS_fsm_state3, ap_predicate_op141_write_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if ((not(((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_block_state1_assign_proc : process(frame_in_V_empty_n, tmp_nbreadreq_fu_154_p3)
    begin
                ap_block_state1 <= ((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0));
    end process;


    ap_block_state3_assign_proc : process(cord_out_V_full_n, ap_predicate_op141_write_state3)
    begin
                ap_block_state3 <= ((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0));
    end process;


    ap_phi_mux_bottom_edge_flag_3_phi_fu_407_p4_assign_proc : process(ap_CS_fsm_state3, tmp_reg_1168, bottom_edge_flag_2_reg_261, bottom_edge_flag_3_reg_404)
    begin
        if (((tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_phi_mux_bottom_edge_flag_3_phi_fu_407_p4 <= bottom_edge_flag_2_reg_261;
        else 
            ap_phi_mux_bottom_edge_flag_3_phi_fu_407_p4 <= bottom_edge_flag_3_reg_404;
        end if; 
    end process;


    ap_phi_mux_bottom_edge_loc_2_phi_fu_286_p4_assign_proc : process(or_cond_7_reg_1172, ap_CS_fsm_state2, p_current_y_cord_load_2_fu_766_p3, bottom_edge_loc_2_reg_283)
    begin
        if (((or_cond_7_reg_1172 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_phi_mux_bottom_edge_loc_2_phi_fu_286_p4 <= p_current_y_cord_load_2_fu_766_p3;
        else 
            ap_phi_mux_bottom_edge_loc_2_phi_fu_286_p4 <= bottom_edge_loc_2_reg_283;
        end if; 
    end process;


    ap_phi_mux_bottom_edge_new_3_phi_fu_418_p4_assign_proc : process(ap_CS_fsm_state3, tmp_reg_1168, bottom_edge_new_2_reg_271, bottom_edge_new_3_reg_414)
    begin
        if (((tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_phi_mux_bottom_edge_new_3_phi_fu_418_p4 <= bottom_edge_new_2_reg_271;
        else 
            ap_phi_mux_bottom_edge_new_3_phi_fu_418_p4 <= bottom_edge_new_3_reg_414;
        end if; 
    end process;


    ap_phi_mux_current_x_cord_flag_1_phi_fu_326_p4_assign_proc : process(ap_CS_fsm_state3, tmp_reg_1168, current_x_cord_flag_1_reg_323)
    begin
        if (((tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_phi_mux_current_x_cord_flag_1_phi_fu_326_p4 <= ap_const_lv1_1;
        else 
            ap_phi_mux_current_x_cord_flag_1_phi_fu_326_p4 <= current_x_cord_flag_1_reg_323;
        end if; 
    end process;


    ap_phi_mux_current_x_cord_new_1_phi_fu_337_p4_assign_proc : process(ap_CS_fsm_state3, tmp_reg_1168, storemerge_fu_1030_p3, current_x_cord_new_1_reg_333)
    begin
        if (((tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_phi_mux_current_x_cord_new_1_phi_fu_337_p4 <= storemerge_fu_1030_p3;
        else 
            ap_phi_mux_current_x_cord_new_1_phi_fu_337_p4 <= current_x_cord_new_1_reg_333;
        end if; 
    end process;


    ap_phi_mux_current_y_cord_flag_2_phi_fu_347_p4_assign_proc : process(ap_CS_fsm_state3, tmp_reg_1168, current_y_cord_flag_1_fu_1007_p2, current_y_cord_flag_2_reg_344)
    begin
        if (((tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_phi_mux_current_y_cord_flag_2_phi_fu_347_p4 <= current_y_cord_flag_1_fu_1007_p2;
        else 
            ap_phi_mux_current_y_cord_flag_2_phi_fu_347_p4 <= current_y_cord_flag_2_reg_344;
        end if; 
    end process;


    ap_phi_mux_current_y_cord_new_2_phi_fu_357_p4_assign_proc : process(ap_CS_fsm_state3, tmp_reg_1168, current_y_cord_new_1_fu_1013_p3, current_y_cord_new_2_reg_353)
    begin
        if (((tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_phi_mux_current_y_cord_new_2_phi_fu_357_p4 <= current_y_cord_new_1_fu_1013_p3;
        else 
            ap_phi_mux_current_y_cord_new_2_phi_fu_357_p4 <= current_y_cord_new_2_reg_353;
        end if; 
    end process;


    ap_phi_mux_left_edge_flag_3_phi_fu_367_p4_assign_proc : process(ap_CS_fsm_state3, tmp_reg_1168, left_edge_flag_2_reg_203, left_edge_flag_3_reg_364)
    begin
        if (((tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_phi_mux_left_edge_flag_3_phi_fu_367_p4 <= left_edge_flag_2_reg_203;
        else 
            ap_phi_mux_left_edge_flag_3_phi_fu_367_p4 <= left_edge_flag_3_reg_364;
        end if; 
    end process;


    ap_phi_mux_left_edge_loc_2_phi_fu_226_p4_assign_proc : process(or_cond_7_reg_1172, ap_CS_fsm_state2, left_edge_loc_1_fu_741_p3, left_edge_loc_2_reg_223)
    begin
        if (((or_cond_7_reg_1172 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_phi_mux_left_edge_loc_2_phi_fu_226_p4 <= left_edge_loc_1_fu_741_p3;
        else 
            ap_phi_mux_left_edge_loc_2_phi_fu_226_p4 <= left_edge_loc_2_reg_223;
        end if; 
    end process;


    ap_phi_mux_left_edge_new_3_phi_fu_377_p4_assign_proc : process(ap_CS_fsm_state3, tmp_reg_1168, left_edge_new_2_reg_213, left_edge_new_3_reg_374)
    begin
        if (((tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_phi_mux_left_edge_new_3_phi_fu_377_p4 <= left_edge_new_2_reg_213;
        else 
            ap_phi_mux_left_edge_new_3_phi_fu_377_p4 <= left_edge_new_3_reg_374;
        end if; 
    end process;


    ap_phi_mux_right_edge_flag_3_phi_fu_429_p4_assign_proc : process(ap_CS_fsm_state3, tmp_reg_1168, right_edge_flag_2_reg_292, right_edge_flag_3_reg_426)
    begin
        if (((tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_phi_mux_right_edge_flag_3_phi_fu_429_p4 <= right_edge_flag_2_reg_292;
        else 
            ap_phi_mux_right_edge_flag_3_phi_fu_429_p4 <= right_edge_flag_3_reg_426;
        end if; 
    end process;


    ap_phi_mux_right_edge_loc_2_phi_fu_317_p4_assign_proc : process(or_cond_7_reg_1172, ap_CS_fsm_state2, p_current_x_cord_load_2_fu_717_p3, right_edge_loc_2_reg_314)
    begin
        if (((or_cond_7_reg_1172 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_phi_mux_right_edge_loc_2_phi_fu_317_p4 <= p_current_x_cord_load_2_fu_717_p3;
        else 
            ap_phi_mux_right_edge_loc_2_phi_fu_317_p4 <= right_edge_loc_2_reg_314;
        end if; 
    end process;


    ap_phi_mux_right_edge_new_3_phi_fu_440_p4_assign_proc : process(ap_CS_fsm_state3, tmp_reg_1168, right_edge_new_2_reg_302, right_edge_new_3_reg_436)
    begin
        if (((tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_phi_mux_right_edge_new_3_phi_fu_440_p4 <= right_edge_new_2_reg_302;
        else 
            ap_phi_mux_right_edge_new_3_phi_fu_440_p4 <= right_edge_new_3_reg_436;
        end if; 
    end process;


    ap_phi_mux_upper_edge_flag_3_phi_fu_387_p4_assign_proc : process(ap_CS_fsm_state3, tmp_reg_1168, upper_edge_flag_2_reg_232, upper_edge_flag_3_reg_384)
    begin
        if (((tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_phi_mux_upper_edge_flag_3_phi_fu_387_p4 <= upper_edge_flag_2_reg_232;
        else 
            ap_phi_mux_upper_edge_flag_3_phi_fu_387_p4 <= upper_edge_flag_3_reg_384;
        end if; 
    end process;


    ap_phi_mux_upper_edge_loc_2_phi_fu_255_p4_assign_proc : process(or_cond_7_reg_1172, ap_CS_fsm_state2, upper_edge_loc_1_fu_790_p3, upper_edge_loc_2_reg_252)
    begin
        if (((or_cond_7_reg_1172 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_phi_mux_upper_edge_loc_2_phi_fu_255_p4 <= upper_edge_loc_1_fu_790_p3;
        else 
            ap_phi_mux_upper_edge_loc_2_phi_fu_255_p4 <= upper_edge_loc_2_reg_252;
        end if; 
    end process;


    ap_phi_mux_upper_edge_new_3_phi_fu_397_p4_assign_proc : process(ap_CS_fsm_state3, tmp_reg_1168, upper_edge_new_2_reg_242, upper_edge_new_3_reg_394)
    begin
        if (((tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_phi_mux_upper_edge_new_3_phi_fu_397_p4 <= upper_edge_new_2_reg_242;
        else 
            ap_phi_mux_upper_edge_new_3_phi_fu_397_p4 <= upper_edge_new_3_reg_394;
        end if; 
    end process;


    ap_predicate_op141_write_state3_assign_proc : process(tmp_reg_1168, tmp_5_reg_1176, tmp_10_reg_1181)
    begin
                ap_predicate_op141_write_state3 <= ((tmp_10_reg_1181 = ap_const_lv1_1) and (tmp_5_reg_1176 = ap_const_lv1_1) and (tmp_reg_1168 = ap_const_lv1_1));
    end process;


    cord_out_V_blk_n_assign_proc : process(cord_out_V_full_n, ap_CS_fsm_state3, tmp_reg_1168, tmp_5_reg_1176, tmp_10_reg_1181)
    begin
        if (((tmp_10_reg_1181 = ap_const_lv1_1) and (tmp_5_reg_1176 = ap_const_lv1_1) and (tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            cord_out_V_blk_n <= cord_out_V_full_n;
        else 
            cord_out_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    cord_out_V_din <= ((ap_const_lv1_1 & p_4_reg_1204) & p_0_fu_973_p3);

    cord_out_V_write_assign_proc : process(cord_out_V_full_n, ap_CS_fsm_state3, ap_predicate_op141_write_state3)
    begin
        if ((not(((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0))) and (ap_predicate_op141_write_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            cord_out_V_write <= ap_const_logic_1;
        else 
            cord_out_V_write <= ap_const_logic_0;
        end if; 
    end process;

    current_y_cord_flag_1_fu_1007_p1 <= (0=>reset, others=>'-');
    current_y_cord_flag_1_fu_1007_p2 <= (grp_fu_453_p2 or current_y_cord_flag_1_fu_1007_p1);
    current_y_cord_new_1_fu_1013_p3 <= 
        storemerge1_fu_995_p3 when (grp_fu_453_p2(0) = '1') else 
        ap_const_lv32_0;
    data_center_V_fu_965_p3 <= (tmp_16_fu_912_p3 & tmp_20_fu_957_p3);
    edgeout_val <= p_4_reg_1204;

    edgeout_val_ap_vld_assign_proc : process(cord_out_V_full_n, ap_CS_fsm_state3, ap_predicate_op141_write_state3)
    begin
        if ((not(((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0))) and (ap_predicate_op141_write_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            edgeout_val_ap_vld <= ap_const_logic_1;
        else 
            edgeout_val_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    frame_in_V_blk_n_assign_proc : process(frame_in_V_empty_n, ap_CS_fsm_state1, tmp_nbreadreq_fu_154_p3)
    begin
        if (((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            frame_in_V_blk_n <= frame_in_V_empty_n;
        else 
            frame_in_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    frame_in_V_read_assign_proc : process(frame_in_V_empty_n, ap_CS_fsm_state1, tmp_nbreadreq_fu_154_p3)
    begin
        if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            frame_in_V_read <= ap_const_logic_1;
        else 
            frame_in_V_read <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_448_p2 <= std_logic_vector(unsigned(width) + unsigned(ap_const_lv32_FFFFFFFF));
    grp_fu_453_p2 <= "1" when (p_current_x_cord_load_reg_1099 = grp_fu_448_p2) else "0";
    height_assign_fu_783_p3 <= 
        p_current_y_cord_load_reg_1111 when (tmp_8_fu_773_p2(0) = '1') else 
        height;
    height_upper_edge_lo_fu_518_p3 <= 
        height when (tmp_4_fu_488_p2(0) = '1') else 
        upper_edge;
    left_edge_flag_1_fu_728_p2 <= (tmp_6_fu_724_p2 or tmp_4_reg_1124);
    left_edge_loc_1_fu_741_p3 <= 
        p_current_x_cord_load_reg_1099 when (tmp_6_fu_724_p2(0) = '1') else 
        width_left_edge_load_reg_1140;
    newSel1_fu_607_p3 <= 
        r_V_1_fu_551_p1 when (sel_tmp_fu_575_p2(0) = '1') else 
        r_V_cast_fu_555_p4;
    newSel2_fu_615_p3 <= 
        newSel_fu_593_p3 when (or_cond_fu_601_p2(0) = '1') else 
        newSel1_fu_607_p3;
    newSel3_fu_623_p3 <= 
        r_V_fu_565_p4 when (sel_tmp4_fu_587_p2(0) = '1') else 
        r_V_cast_fu_555_p4;
    newSel4_fu_631_p3 <= 
        r_V_cast_fu_555_p4 when (sel_tmp_fu_575_p2(0) = '1') else 
        r_V_fu_565_p4;
    newSel_fu_593_p3 <= 
        r_V_cast_fu_555_p4 when (sel_tmp4_fu_587_p2(0) = '1') else 
        r_V_fu_565_p4;
    or_cond_7_fu_687_p2 <= (tmp1_fu_681_p2 and other1_below_fu_669_p2);
    or_cond_fu_601_p2 <= (sel_tmp4_fu_587_p2 or sel_tmp2_fu_581_p2);
    other1_below_fu_669_p2 <= "1" when (unsigned(r_V_2_fu_639_p3) < unsigned(other_threshold)) else "0";
    other2_below_fu_663_p2 <= "1" when (unsigned(r_V_3_fu_655_p3) < unsigned(other_threshold)) else "0";
    p_0_fu_973_p3 <= 
        data_center_V_fu_965_p3 when (led_exist_load_reg_1185(0) = '1') else 
        ap_const_lv32_FFFFFFFF;
    p_4_fu_867_p3 <= 
        val_assign_fu_861_p2 when (led_exist(0) = '1') else 
        ap_const_lv64_FFFFFFFF;
    p_bottom_edge_load_fu_526_p3 <= 
        ap_const_lv32_0 when (tmp_4_fu_488_p2(0) = '1') else 
        bottom_edge;
    p_current_x_cord_load_1_fu_709_p3 <= 
        p_current_x_cord_load_reg_1099 when (tmp_s_fu_699_p2(0) = '1') else 
        ap_const_lv32_0;
    p_current_x_cord_load_2_fu_717_p3 <= 
        p_current_x_cord_load_reg_1099 when (tmp_s_fu_699_p2(0) = '1') else 
        p_right_edge_load_reg_1161;
    p_current_x_cord_load_fu_466_p0 <= (0=>reset, others=>'-');
    p_current_x_cord_load_fu_466_p3 <= 
        ap_const_lv32_0 when (p_current_x_cord_load_fu_466_p0(0) = '1') else 
        current_x_cord;
    p_current_y_cord_load_1_fu_758_p3 <= 
        p_current_y_cord_load_reg_1111 when (tmp_7_fu_748_p2(0) = '1') else 
        ap_const_lv32_0;
    p_current_y_cord_load_2_fu_766_p3 <= 
        p_current_y_cord_load_reg_1111 when (tmp_7_fu_748_p2(0) = '1') else 
        p_bottom_edge_load_reg_1154;
    p_current_y_cord_load_fu_474_p0 <= (0=>reset, others=>'-');
    p_current_y_cord_load_fu_474_p3 <= 
        ap_const_lv32_0 when (p_current_y_cord_load_fu_474_p0(0) = '1') else 
        current_y_cord;
    p_left_edge_flag1_fu_752_p2 <= (tmp_7_fu_748_p2 or tmp_4_reg_1124);
    p_left_edge_flag_fu_703_p2 <= (tmp_s_fu_699_p2 or tmp_4_reg_1124);
    p_neg1_fu_882_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(tmp_11_reg_1190));
    p_neg_fu_927_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(tmp_14_reg_1197));
    p_right_edge_load_fu_534_p3 <= 
        ap_const_lv32_0 when (tmp_4_fu_488_p2(0) = '1') else 
        right_edge;
    pixel_in_data_out <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_21_fu_542_p1),32));

    pixel_in_data_out_ap_vld_assign_proc : process(frame_in_V_empty_n, ap_CS_fsm_state1, tmp_nbreadreq_fu_154_p3)
    begin
        if ((not(((tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (frame_in_V_empty_n = ap_const_logic_0))) and (tmp_nbreadreq_fu_154_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            pixel_in_data_out_ap_vld <= ap_const_logic_1;
        else 
            pixel_in_data_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    r_V_1_fu_551_p1 <= frame_in_V_dout(8 - 1 downto 0);
    r_V_2_fu_639_p3 <= 
        newSel3_fu_623_p3 when (or_cond_fu_601_p2(0) = '1') else 
        newSel4_fu_631_p3;
    r_V_3_fu_655_p3 <= 
        r_V_1_fu_551_p1 when (or_cond_fu_601_p2(0) = '1') else 
        tmp_1_fu_647_p3;
    r_V_cast_fu_555_p4 <= frame_in_V_dout(23 downto 16);
    r_V_fu_565_p4 <= frame_in_V_dout(15 downto 8);
    sel_tmp2_fu_581_p2 <= "1" when (target_color = ap_const_lv8_2) else "0";
    sel_tmp4_fu_587_p2 <= "1" when (target_color = ap_const_lv8_1) else "0";
    sel_tmp_fu_575_p2 <= "1" when (target_color = ap_const_lv8_3) else "0";
    storemerge1_fu_995_p3 <= 
        ap_const_lv32_0 when (tmp_5_reg_1176(0) = '1') else 
        tmp_26_fu_990_p2;
    storemerge_fu_1030_p3 <= 
        ap_const_lv32_0 when (grp_fu_453_p2(0) = '1') else 
        tmp_27_fu_1002_p2;
    target_above_fu_675_p2 <= "1" when (unsigned(newSel2_fu_615_p3) > unsigned(target_threshold)) else "0";
    tmp1_fu_681_p2 <= (target_above_fu_675_p2 and other2_below_fu_663_p2);
    tmp_11_fu_819_p2 <= std_logic_vector(unsigned(ap_phi_mux_right_edge_loc_2_phi_fu_317_p4) + unsigned(ap_phi_mux_left_edge_loc_2_phi_fu_226_p4));
    tmp_12_fu_887_p4 <= p_neg1_fu_882_p2(16 downto 1);
    tmp_13_fu_897_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(tmp_12_fu_887_p4));
    tmp_14_fu_825_p2 <= std_logic_vector(unsigned(ap_phi_mux_bottom_edge_loc_2_phi_fu_286_p4) + unsigned(ap_phi_mux_upper_edge_loc_2_phi_fu_255_p4));
    tmp_15_fu_903_p4 <= tmp_11_reg_1190(16 downto 1);
    tmp_16_fu_912_p3 <= 
        tmp_13_fu_897_p2 when (tmp_31_fu_875_p3(0) = '1') else 
        tmp_15_fu_903_p4;
    tmp_17_fu_932_p4 <= p_neg_fu_927_p2(16 downto 1);
    tmp_18_fu_942_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(tmp_17_fu_932_p4));
    tmp_19_fu_948_p4 <= tmp_14_reg_1197(16 downto 1);
    tmp_1_fu_647_p3 <= 
        r_V_fu_565_p4 when (sel_tmp_fu_575_p2(0) = '1') else 
        r_V_1_fu_551_p1;
    tmp_20_fu_957_p3 <= 
        tmp_18_fu_942_p2 when (tmp_32_fu_920_p3(0) = '1') else 
        tmp_19_fu_948_p4;
    tmp_21_fu_542_p1 <= frame_in_V_dout(24 - 1 downto 0);
    tmp_22_fu_839_p3 <= (tmp_34_fu_835_p1 & tmp_29_fu_797_p1);
    tmp_23_fu_851_p4 <= ((tmp_33_fu_831_p1 & tmp_30_fu_801_p1) & ap_const_lv32_0);
    tmp_26_fu_990_p2 <= std_logic_vector(unsigned(p_current_y_cord_load_reg_1111) + unsigned(ap_const_lv32_1));
    tmp_27_fu_1002_p2 <= std_logic_vector(unsigned(p_current_x_cord_load_reg_1099) + unsigned(ap_const_lv32_1));
    tmp_29_fu_797_p1 <= ap_phi_mux_bottom_edge_loc_2_phi_fu_286_p4(16 - 1 downto 0);
    tmp_30_fu_801_p1 <= ap_phi_mux_right_edge_loc_2_phi_fu_317_p4(16 - 1 downto 0);
    tmp_31_fu_875_p3 <= tmp_11_reg_1190(31 downto 31);
    tmp_32_fu_920_p3 <= tmp_14_reg_1197(31 downto 31);
    tmp_33_fu_831_p1 <= ap_phi_mux_left_edge_loc_2_phi_fu_226_p4(16 - 1 downto 0);
    tmp_34_fu_835_p1 <= ap_phi_mux_upper_edge_loc_2_phi_fu_255_p4(16 - 1 downto 0);
    tmp_3_fu_482_p2 <= (p_current_y_cord_load_fu_474_p3 or p_current_x_cord_load_fu_466_p3);
    tmp_4_fu_488_p2 <= "1" when (tmp_3_fu_482_p2 = ap_const_lv32_0) else "0";
    tmp_5_fu_810_p2 <= "1" when (p_current_y_cord_load_reg_1111 = tmp_9_fu_805_p2) else "0";
    tmp_6_fu_724_p2 <= "1" when (signed(p_current_x_cord_load_reg_1099) < signed(width_left_edge_load_reg_1140)) else "0";
    tmp_7_fu_748_p2 <= "1" when (signed(p_current_y_cord_load_reg_1111) > signed(p_bottom_edge_load_reg_1154)) else "0";
    tmp_8_fu_773_p2 <= "1" when (signed(p_current_y_cord_load_reg_1111) < signed(height_upper_edge_lo_reg_1147)) else "0";
    tmp_9_fu_805_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFFF) + signed(height));
    tmp_nbreadreq_fu_154_p3 <= (0=>frame_in_V_empty_n, others=>'-');
    tmp_s_fu_699_p2 <= "1" when (signed(p_current_x_cord_load_reg_1099) > signed(p_right_edge_load_reg_1161)) else "0";
        ud_edge_fu_847_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_22_fu_839_p3),64));

    upper_edge_flag_1_fu_777_p2 <= (tmp_8_fu_773_p2 or tmp_4_reg_1124);
    upper_edge_loc_1_fu_790_p3 <= 
        p_current_y_cord_load_reg_1111 when (tmp_8_fu_773_p2(0) = '1') else 
        height_upper_edge_lo_reg_1147;
    val_assign_fu_861_p2 <= (ud_edge_fu_847_p1 or tmp_23_fu_851_p4);
    width_assign_fu_734_p3 <= 
        p_current_x_cord_load_reg_1099 when (tmp_6_fu_724_p2(0) = '1') else 
        width;
    width_left_edge_load_fu_510_p3 <= 
        width when (tmp_4_fu_488_p2(0) = '1') else 
        left_edge;
    x_cord_out <= 
        ap_const_lv32_0 when (grp_fu_453_p2(0) = '1') else 
        tmp_27_fu_1002_p2;

    x_cord_out_ap_vld_assign_proc : process(cord_out_V_full_n, ap_CS_fsm_state3, tmp_reg_1168, ap_predicate_op141_write_state3)
    begin
        if ((not(((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0))) and (tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            x_cord_out_ap_vld <= ap_const_logic_1;
        else 
            x_cord_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    y_cord_out <= 
        storemerge1_fu_995_p3 when (grp_fu_453_p2(0) = '1') else 
        p_current_y_cord_load_reg_1111;

    y_cord_out_ap_vld_assign_proc : process(cord_out_V_full_n, ap_CS_fsm_state3, tmp_reg_1168, ap_predicate_op141_write_state3)
    begin
        if ((not(((ap_predicate_op141_write_state3 = ap_const_boolean_1) and (cord_out_V_full_n = ap_const_logic_0))) and (tmp_reg_1168 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            y_cord_out_ap_vld <= ap_const_logic_1;
        else 
            y_cord_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
